# Generated by Django 2.2.1 on 2019-05-17 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingitem',
            name='reading_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='readings.ReadingList'),
        ),
    ]
